services:
  inner-relay:
    container_name: inner-relay
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./.env:/app/.env
      - ./users.json:/app/users.json
      - db:/app/db
    ports:
      - "${EXPOSED_DOCKER_PORT}:${RELAY_PORT}"
    restart: unless-stopped

volumes:
  db:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./db