version: '3'

services:
  khatru-invite:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3334:3334
    volumes:
      - ./users.json:/app/users.json
      - ./db:/app/db
    env_file:
      - .env
