name: build for all platforms

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  releases-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, freebsd, darwin, windows]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.40
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          overwrite: true
          md5sum: false
          sha256sum: false
          compress_assets: false
